### ISSUE TITLE
Scans not starting anymore

### ISSUE THREAD

**Issue by jpohls1** [VirusTotal/yara-ci-issues#17] opened 2023-08-07 11:00 UTC
Same issue as reported some time back in https://github.com/VirusTotal/yara-ci-issues/issues/12 is hitting us now. It worked before but stopped working on 7th August 2023 around 12:00 CEST.
<img width="488" alt="image" src="https://github.com/VirusTotal/yara-ci-issues/assets/105008167/d4cb32cb-2011-4fec-9e88-c9ff16261795">

**Comment by Zohiartze** [comment] 2023-09-20 07:18
Hi @jpohls1 thanks for reporting this issue. It was caused by yara-ci going too high in memory consumption under certain conditions. We made the fix and it and has been deployed for a while so I'm closing this issue.

**Closed as completed by Zohiartze** 2023-09-20 07:18 UTC
